---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: $(es_storage_class)
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-pv-local-storage-0  # Local volumes do not currently support dynamic provisioning, per https://kubernetes.io/docs/concepts/storage/storage-classes/#local
  labels:
      type: local
spec:
  storageClassName: es-local-storage
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/es-data-0"        
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-pv-local-storage-1
  labels:
      type: local
spec:
  storageClassName: es-local-storage
  capacity:
    storage: 6Gi        
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/es-data-1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-pv-local-storage-2
  labels:
      type: local
spec:
  storageClassName: es-local-storage
  capacity:
    storage: 6Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/es-data-2"
